server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://8.130.55.35:3306/ityyp_blog?encharacterEncoding=utf-8serverTimezone=UTC&useSSL=false
    username: root
    password: '@yypAa123456'
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 2MB
  redis:
    host: 8.130.55.35
    password: '@yypAa123456'

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oss:
  accessKey: aW43qRDO3j2RU1z0Qig1HMcp-pSA2NX0pIVOX7Dp
  secretKey: tocpEd-dv9hnCrrMt45qCgIbt6WiGhJK5tGXGv6_
  bucket: ityyp-blog
